### ISSUE TITLE
Result code: 0

### ISSUE THREAD

**Issue by andreluisjunqueira** [genyaonipko/react-native-sms-user-consent#1]
It often gives the message "Result code: 0" and close the app.

**Comment by genyaonipko** [comment]
@andreluisjunqueira can you give me more details? 
Android version, simulator or real device, it happens when you cancel modal?
it gives often or it is always?

And did you added this lines in your build.gradle file?
`
implementation 'com.google.android.gms:play-services-auth:17.0.0'
implementation 'com.google.android.gms:play-services-auth-api-phone:17.4.0'
`
